import { db, Feedback, AppMapping } from 'astro:db';

// https://astro.build/db/seed
export default async function seed() {
	await db.insert(Feedback).values([
		{ progress: 2, email: 'xyz-2@yahoo.co', content: 'Intriguing', slug: 'aat/contents', rating: 0},
		{ progress: 2, email: 'xyz-1@gmail.com', content: `This isn't quite right, it needs to be better worded. The 'Specific' field alone in the Machine Center card will influence that the Routing Line 'Unit Cost Per' value is used, in the same way as occurs for Work Center. Separately, the field 'Use Specific Cost as Direct', for either of WC or MC, will be respected by these reports in calculating how Indirect and Overhead Costs are calculated in addition to (as opposed to deducted from) the Routing Line 'Unit Cost Per'.`, slug: 'aac/aptean-azure-connector', rating: -1},
		{ progress: 1, email: 'xyz-3@yahoo.co', content: 'Amazing, Splendid!', slug: 'aac/deployment-instructions', rating: 1},
		{ progress: 1, email: 'xyz-1@gmail.com', content: `I feel that some of this introduction is saying the same thing over and over, it's also a bit incorrect, so I'm going to give my shot at what I think it should say. Essentially, the 4 paragraphs are broken up into: intro, price matrix, alternate costs, pricing inquiry. I think this strongly conveys the power of the app, but stays concise. Feel free to adjust the wording, this is only a suggestion. Introduction The Aptean Pricing Matrix extension is designed to simplify and automate the process of assigning prices for items. This extension uses pricing formulas to provide a way to implement cost-plus pricing. The Price Calculation Matrix allows for different combinations of pricing based on various factors such as customers, customer price groups, customer attributes, items, item attributes, or unit of measure. The basis for pricing calculations comes from custom defined Alternate Costs that can be maintained in a periodic fashion. This allows for market trends to immediately impact pricing by being the source of many customers' pricing. An Alternate Cost Worksheet can be employed to help set and maintain these diverse alternate costs. Easily and quickly lookup customer pricing through the Pricing Inquiry page to see what a customer's price would be for certain items on a certain date without needing to enter a sales order.`, slug: 'aac/aptean-azure-connector', rating: -1},
		{ progress: 1, email: 'xyz-2@yahoo.co', content: 'Intriguing', slug: 'aat/item-attributes', rating: 0},
		{ progress: 2, email: 'xyz-3@yahoo.co', content: 'Amazing, Splendid!', slug: 'aat/contents', rating: 1},
		{ progress: 2, email: 'xyz-1@gmail.com', content: `This isn't quite right, it needs to be better worded. The 'Specific' field alone in the Machine Center card will influence that the Routing Line 'Unit Cost Per' value is used, in the same way as occurs for Work Center. Separately, the field 'Use Specific Cost as Direct', for either of WC or MC, will be respected by these reports in calculating how Indirect and Overhead Costs are calculated in addition to (as opposed to deducted from) the Routing Line 'Unit Cost Per'.`, slug: 'aac/aptean-azure-connector', rating: -1},
		{ progress: 2, email: 'xyz-2@yahoo.co', content: 'Intriguing', slug: 'aat/contents', rating: 0},
		{ progress: 2, email: 'xyz-3@yahoo.co', content: 'Amazing, Splendid!', slug: 'aat/contents', rating: 1},
		{ progress: 2, email: 'xyz-1@gmail.com', content: `This isn't quite right, it needs to be better worded. The 'Specific' field alone in the Machine Center card will influence that the Routing Line 'Unit Cost Per' value is used, in the same way as occurs for Work Center. Separately, the field 'Use Specific Cost as Direct', for either of WC or MC, will be respected by these reports in calculating how Indirect and Overhead Costs are calculated in addition to (as opposed to deducted from) the Routing Line 'Unit Cost Per'.`, slug: 'aac/aptean-azure-connector', rating: -1},
		{ progress: 2, email: 'xyz-2@yahoo.co', content: 'Intriguing', slug: 'aat/contents', rating: 0},
		{ progress: 2, email: 'xyz-3@yahoo.co', content: 'Amazing, Splendid!', slug: 'aat/contents', rating: 1},
		{ progress: 2, email: 'xyz-1@gmail.com', content: `This isn't quite right, it needs to be better worded. The 'Specific' field alone in the Machine Center card will influence that the Routing Line 'Unit Cost Per' value is used, in the same way as occurs for Work Center. Separately, the field 'Use Specific Cost as Direct', for either of WC or MC, will be respected by these reports in calculating how Indirect and Overhead Costs are calculated in addition to (as opposed to deducted from) the Routing Line 'Unit Cost Per'.`, slug: 'aac/aptean-azure-connector', rating: -1},
		{ progress: 2, email: 'xyz-2@yahoo.co', content: 'Intriguing', slug: 'aat/contents', rating: 0},
		{ progress: 2, email: 'xyz-3@yahoo.co', content: 'Amazing, Splendid!', slug: 'aat/contents', rating: 1},
		{ progress: 2, email: 'xyz-1@gmail.com', content: `This isn't quite right, it needs to be better worded. The 'Specific' field alone in the Machine Center card will influence that the Routing Line 'Unit Cost Per' value is used, in the same way as occurs for Work Center. Separately, the field 'Use Specific Cost as Direct', for either of WC or MC, will be respected by these reports in calculating how Indirect and Overhead Costs are calculated in addition to (as opposed to deducted from) the Routing Line 'Unit Cost Per'.`, slug: 'aac/aptean-azure-connector', rating: -1},
		{ progress: 2, email: 'xyz-2@yahoo.co', content: 'Intriguing', slug: 'aat/contents', rating: 0},
		{ progress: 2, email: 'xyz-3@yahoo.co', content: 'Amazing, Splendid!', slug: 'aat/contents', rating: 1},
		{ progress: 2, email: 'xyz-1@gmail.com', content: `This isn't quite right, it needs to be better worded. The 'Specific' field alone in the Machine Center card will influence that the Routing Line 'Unit Cost Per' value is used, in the same way as occurs for Work Center. Separately, the field 'Use Specific Cost as Direct', for either of WC or MC, will be respected by these reports in calculating how Indirect and Overhead Costs are calculated in addition to (as opposed to deducted from) the Routing Line 'Unit Cost Per'.`, slug: 'aac/aptean-azure-connector', rating: -1},
		{ progress: 1, email: 'xyz-2@yahoo.co', content: 'Intriguing', slug: 'aat/contents', rating: 0},
		{ progress: 1, email: 'xyz-3@yahoo.co', content: 'Amazing, Splendid!', slug: 'aat/contents', rating: 1},
		{ progress: 0, email: 'xyz-1@gmail.com', content: `This isn't quite right, it needs to be better worded. The 'Specific' field alone in the Machine Center card will influence that the Routing Line 'Unit Cost Per' value is used, in the same way as occurs for Work Center. Separately, the field 'Use Specific Cost as Direct', for either of WC or MC, will be respected by these reports in calculating how Indirect and Overhead Costs are calculated in addition to (as opposed to deducted from) the Routing Line 'Unit Cost Per'.`, slug: 'aac/aptean-azure-connector', rating: -1},
		{ progress: 0, email: 'xyz-2@yahoo.co', content: 'Intriguing', slug: 'aat/contents', rating: 0},
		{ progress: 2, email: 'xyz-3@yahoo.co', content: 'Amazing, Splendid!', slug: 'aat/contents', rating: 1},
		{ progress: 2, email: 'xyz-1@gmail.com', content: `This isn't quite right, it needs to be better worded. The 'Specific' field alone in the Machine Center card will influence that the Routing Line 'Unit Cost Per' value is used, in the same way as occurs for Work Center. Separately, the field 'Use Specific Cost as Direct', for either of WC or MC, will be respected by these reports in calculating how Indirect and Overhead Costs are calculated in addition to (as opposed to deducted from) the Routing Line 'Unit Cost Per'.`, slug: 'aac/aptean-azure-connector', rating: -1},
		{ progress: 0, email: 'xyz-2@yahoo.co', content: 'Intriguing', slug: 'aat/contents', rating: 0},
		{ progress: 0, email: 'xyz-3@yahoo.co', content: 'Amazing, Splendid!', slug: 'aat/contents', rating: 1},
	]);

	// @ts-ignore
	const appMappingCSV = (await import('./app-mapping.csv')).default as {short: string, long: string}[]
	console.log(appMappingCSV);

	await db.insert(AppMapping).values(appMappingCSV);
}
